### ISSUE TITLE
Weird formatting on patient form when errors are encountered

### ISSUE THREAD

**Issue by samkotlove** [Photon-Health/client#192]
<img width="754" alt="Screen Shot 2023-04-03 at 5 59 23 PM" src="https://user-images.githubusercontent.com/8848487/229636767-792a574d-9567-4552-b16f-b81a37e2880b.png">

**Comment by captDaylight** [comment]
duplicate of #181 #168 should be up on production soon

**Comment by samkotlove** [comment]
My bad! 🙈
