### ISSUE TITLE
Prescription screen is missing instructions (SIG)

### ISSUE THREAD

**Issue by samkotlove** [Photon-Health/client#232]
<img width="734" alt="Screen Shot 2023-04-18 at 10 45 51 AM" src="https://user-images.githubusercontent.com/8848487/232813840-e3d27034-c3c2-4ccd-bbe9-de9e7556d107.png">

If you go to to the prescription screen and look at details you'll see that Pharmacy notes are included but not patient instructions (sig). We should let the provider see all details about the prescription on that screen

**Comment by captDaylight** [comment]
I'm seeing it above notes, maybe we should clarify the headers @samkotlove ?
<img width="803" alt="Screen Shot 2023-04-19 at 2 40 49 PM" src="https://user-images.githubusercontent.com/700617/233182478-3a891c72-8a8d-4ac5-8130-ff0ce111ee5a.png">
