### ISSUE TITLE
Orders page shows order fulfillment status when top level order status makes more sense

### ISSUE THREAD

**Issue by samkotlove** [Photon-Health/client#242]
It looks like the orders table shows the order fulfillment as the status, which is confusing in the case where it's canceled and the fulfillment status is `sent` or `recevied`, when the doctor would only care about it being `canceled`

[Slack comment](https://photonhealth.slack.com/archives/C033T9N949M/p1682266018105129)

**Comment by jknapp25** [comment]
@samkotlove in the table we say the column is  fulfillment status

<img width="163" alt="image" src="https://user-images.githubusercontent.com/3934326/236512905-19acc715-6a5a-4c2c-869f-fe0e7ca0e33f.png">

Is a good solution for this, to rename the column to "Status" and surface fulfillment or top level at different times?

**Comment by samkotlove** [comment]
> Wondering if a good solution here is to rename the column to "Status" and surface fulfillment or top level at different times?

Yeah I agree with that!
