### ISSUE TITLE
Canceled button is still showing for orders that are in canceled state

### ISSUE THREAD

**Issue by samkotlove** [Photon-Health/client#267]
<img width="737" alt="Screen Shot 2023-05-02 at 5 16 52 PM" src="https://user-images.githubusercontent.com/8848487/235788202-feac3525-fe38-4c7b-a379-f80118d31953.png">
(From Neutron)
The canceled button shouldn't show (or should be disabled) for orders that have already been canceled

**Comment by JayeshJanyani** [comment]
I can work on this, please assign it to me.

**Comment by JayeshJanyani** [comment]
@samkotlove can you please help me setup this repo. I am getting stuck on blank screen with loader after login.                      <TagLabel>{ORDER_STATE_MAP[order.state as keyof object] || ''}</TagLabel>
